name: MinehutFriends
version: '${project.version}'
main: sh.astrid.minehutfriends.MinehutFriends
api-version: 1.19
authors: [ astrid ]
softdepend: [ Skript ]
description: A plugin to award players for inviting friends